#ifndef NMFBIOMASSMODEL_GLOBAL_H
#define NMFBIOMASSMODEL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NMFBIOMASSMODEL_LIBRARY)
#  define NMFBIOMASSMODELSHARED_EXPORT Q_DECL_EXPORT
#else
#  define NMFBIOMASSMODELSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NMFBIOMASSMODEL_GLOBAL_H
