#ifndef NMFENTITYMODEL_GLOBAL_H
#define NMFENTITYMODEL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NMFENTITYMODEL_LIBRARY)
#  define NMFENTITYMODELSHARED_EXPORT Q_DECL_EXPORT
#else
#  define NMFENTITYMODELSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NMFENTITYMODEL_GLOBAL_H
