#ifndef NMFINITIALSELECTIVITY_GLOBAL_H
#define NMFINITIALSELECTIVITY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NMFINITIALSELECTIVITY_LIBRARY)
#  define NMFINITIALSELECTIVITYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define NMFINITIALSELECTIVITYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NMFINITIALSELECTIVITY_GLOBAL_H
