#ifndef NMFMATURITYMODEL_GLOBAL_H
#define NMFMATURITYMODEL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NMFMATURITYMODEL_LIBRARY)
#  define NMFMATURITYMODELSHARED_EXPORT Q_DECL_EXPORT
#else
#  define NMFMATURITYMODELSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NMFMATURITYMODEL_GLOBAL_H
