#ifndef NMFMODELDELEGATES_GLOBAL_H
#define NMFMODELDELEGATES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NMFMODELDELEGATES_LIBRARY)
#  define NMFMODELDELEGATESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define NMFMODELDELEGATESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NMFMODELDELEGATES_GLOBAL_H
