#ifndef NMFVONBERTMODEL_GLOBAL_H
#define NMFVONBERTMODEL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NMFVONBERTMODEL_LIBRARY)
#  define NMFVONBERTMODELSHARED_EXPORT Q_DECL_EXPORT
#else
#  define NMFVONBERTMODELSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NMFVONBERTMODEL_GLOBAL_H
