#ifndef NMFVARFISHMORTMODEL_GLOBAL_H
#define NMFVARFISHMORTMODEL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NMFVARFISHMORTMODEL_LIBRARY)
#  define NMFVARFISHMORTMODELSHARED_EXPORT Q_DECL_EXPORT
#else
#  define NMFVARFISHMORTMODELSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NMFVARFISHMORTMODEL_GLOBAL_H
