#ifndef NMFUTILITIES_GLOBAL_H
#define NMFUTILITIES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NMFUTILITIES_LIBRARY)
#  define NMFUTILITIESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define NMFUTILITIESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NMFUTILITIES_GLOBAL_H
