#ifndef NMFGUICOMPONENTSMAIN_GLOBAL_H
#define NMFGUICOMPONENTSMAIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NMFGUICOMPONENTSMAIN_LIBRARY)
#  define NMFGUICOMPONENTSMAINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define NMFGUICOMPONENTSMAINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NMFGUICOMPONENTSMAIN_GLOBAL_H
