
/**
 * @file nmfLogWidget.h
 * @brief Definition for the Logger dock widget
 * @date Dec 8, 2016
 *
 * This file contains the definition for the Logger dock widget. The Logger is capable
 * of displaying log messages generated by the application. Log messages are kept in data
 * files. The Logger can also be used to look at an MSSPM log from a previous run.
 *
 * @copyright
 * Public Domain Notice\n
 *
 * National Oceanic And Atmospheric Administration\n\n
 *
 * This software is a "United States Government Work" under the terms of the
 * United States Copyright Act.  It was written as part of the author's official
 * duties as a United States Government employee/contractor and thus cannot be copyrighted.
 * This software is freely available to the public for use. The National Oceanic
 * And Atmospheric Administration and the U.S. Government have not placed any
 * restriction on its use or reproduction.  Although all reasonable efforts have
 * been taken to ensure the accuracy and reliability of the software and data,
 * the National Oceanic And Atmospheric Administration and the U.S. Government
 * do not and cannot warrant the performance or results that may be obtained
 * by using this software or data. The National Oceanic And Atmospheric
 * Administration and the U.S. Government disclaim all warranties, express
 * or implied, including warranties of performance, merchantability or fitness
 * for any particular purpose.\n\n
 *
 * Please cite the author(s) in any work or product based on this material.
 */

#ifndef NMFLOGWIDGET_H
#define NMFLOGWIDGET_H

#include <QtCharts/QChartView>
#include <QtCharts/QChart>

#include <QDockWidget>
#include <QFile>
#include <QFileDialog>
#include <QFileInfo>
#include <QGroupBox>
#include <QHBoxLayout>
#include <QVBoxLayout>
#include <QLabel>
#include <QPushButton>
#include <QMessageBox>
#include <QScrollBar>
#include <QSpacerItem>
#include <QTextEdit>
#include <QTextStream>

#include "nmfUtils.h"
#include "nmfLogger.h"

QT_CHARTS_USE_NAMESPACE

/**
 * @brief The nmfLogWidget class which allows the user to view current log messages or
 * log messages from previous runs.
 */
class nmfLogWidget : public QObject
{

    Q_OBJECT

private:
    nmfLogger*  m_logger;
    std::string m_logDir;

public:

    QLabel      *filenameLBL;
    QTextEdit   *logTE;
    QGroupBox   *controlsGB;
    QHBoxLayout *hMainLayt;
    QVBoxLayout *vMainLayt;
    QVBoxLayout *vGroupLayt;
    QPushButton *browsePB;
    QPushButton *refreshPB;

    /**
     * @brief nmfLogWidget class constructor
     * @param logger : pointer to the application logger
     * @param logDir : directory to where log files are written
     */
    nmfLogWidget(nmfLogger*  logger,
                 std::string logDir);
   ~nmfLogWidget();

    /**
     * @brief Load the named log file into the logger dock widget
     * @param filename : name of log file to load
     */
    void loadLogFile(QString filename);

public Q_SLOTS:
    /**
     * @brief Callback invoked when the user clicks the Refresh button.  This
     * causes the current log file to be re-read and any updates displayed
     * in the logger dock widget.
     */
    void callback_refreshPB();
    /**
     * @brief Callback invoked when the user clicks the Browse button. This
     * causes a file dialog to appear and allows the user to choose a previously
     * saved log file to display.
     */
    void callback_browsePB();
};


#endif // NMFLOGWIDGET_H
